fix #152
On the nightly build, I couldn't reproduce the reported error, but here
is another example to reproduce it:
```julia
julia> descend((Tuple{Float64,Vararg{Float64}},); optimize=false) do itr
           s = 0
           for a in itr
               s += a
           end
           return s
       end
ERROR: AssertionError: argextype only works on argument-position values
Stacktrace:
  [1] argextype(x::Any, src::Core.CodeInfo, sptypes::Vector{Any}, slottypes::Vector{Any})
    @ Core.Compiler ./compiler/utilities.jl:229
```

It turns out that this error came from `slot = x` statements in an
unoptimized IR, which `argextype` doesn't handle (because it's supposed
to only work on optimized ones).

This PR special cases such statements when working on unoptimized IRs,
and it seems to fix the error.